"""add source_type and source_config to sources

Revision ID: ebfd007e54ab
Revises: b1234567890a
Create Date: 2026-01-28 19:32:47.943690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebfd007e54ab"
down_revision: Union[str, Sequence[str], None] = "b1234567890a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources", sa.Column("source_type", sa.String(length=50), nullable=False)
    )
    op.add_column("sources", sa.Column("source_config", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "source_config")
    op.drop_column("sources", "source_type")
    # ### end Alembic commands ###
